name: CI + Deployment

on:
  push:
    branches: [ 'github-actions-deployment' ] # TODO: Change later

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Even though we only deploy on a specific version of ruby,
        # it's useful to test on multiple versions (to support future updates).
        ruby-version: ['2.6.5', '2.7.5']
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - uses: actions/checkout@v2
      - name: Install libxslt for nokogiri gem (required for version < 1.11)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Run tests
        run: bundle exec rake test

  deploy-to-s3:
    needs: ci # This job should only run after the ci job completes successfully
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Install libxslt for nokogiri gem (required for version < 1.11)
        run: sudo apt-get install -y libxml2-dev libxslt-dev
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # We build and deploy with a specific version of ruby
          ruby-version: '2.7.5'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Deployment
        uses: reggionick/s3-deploy@v3
        with:
            folder: _site
            bucket: cul-s3-dlst-travis-studio-staging
            bucket-region: us-west-2
